#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.7.8 + Manual Fix for Internal DAC */

#define L10N_LANGUAGE			RU

/* Настройки дисплея */
#define DSP_MODEL			DSP_ILI9341
#define TFT_DC			    21
#define TFT_CS			    22
#define BRIGHTNESS_PIN		32

/* Настройки ЗВУКА: Внутренний ЦАП ESP32 */
#define I2S_INTERNAL        true   // ВКЛЮЧАЕМ ВНУТРЕННИЙ ЦАП
#define VS1053_CS           255    // Выключаем VS1053

/* Пины внутреннего ЦАП жестко привязаны к 25 и 26 */
#define I2S_DOUT			25     // Левый канал
#define I2S_LRC			    26     // Правый канал
#define I2S_BCLK			255    // Не используется для внутреннего ЦАП

/* Управление */
#define BTN_MODE			14

#define ENC_BTNR			12
#define ENC_BTNL			33
#define ENC_BTNB			13
#define ENC_INTERNALPULLUP	true
#define ENC_HALFQUARD       false

#define ENC2_BTNR           36
#define ENC2_BTNL           34
#define ENC2_BTNB           39
#define ENC2_INTERNALPULLUP true
#define ENC2_HALFQUARD      false

/* Тачскрин */
#define TS_MODEL			TS_MODEL_XPT2046
#define TS_CS			    4

/* Дополнительные опции */
#define VOLUME_STEP           1 
#define BUFLEN              190
#define BITRATE_FULL          1
#define VOLUME_LOGARITHMIC true 

#endif
